
NAPARI_CFG_SUMMARY_SENTENCE_PATTERN = '(?:summary\:\s)(.*?)(?=\s\n)'
NAPARI_CFG_SOURCE_CODE_PATTERN = '(?:Project\sSite\:\s)(.*?)(?=\s)'
NAPARI_CFG_AUTHOR_PATTERN = '(?:\-\sname\:\s)(.*?)(?=\s\n)'
NAPARI_CFG_BUG_TRACKER_PATTERN = '(?:Bug\sTracker\:\s)(.*?)(?=\s)'
NAPARI_CFG_REPORT_ISSUES_PATTERN = '(?:Report\sIssues\:\s)(.*?)(?=\s)'
NAPARI_CFG_USER_SUPPORT_PATTERN = '(?:User\sSupport\:\s)(.*?)(?=\s)'

NPE2_DISPLAY_NAME_PATTERN = '(?:\sname\:\s)(.*?)(?=\s\n)'
NPE2_SETUPCFG_MANIFEST_PATTERN = '(?=napari.manifest\s\=)(.*?)(?:\.yaml\n)'
NPE2_SETUPCFG_FILE_PATTERN = '(?:\:)(.*?)(?=\'\])'
NPE2_SETUPPY_ENTRYPOINTS_PATTERN = '(?=entry_points\=\{)(.*?)(?:\})'
NPE2_SETUPPY_MANIFEST_FIELD_PATTERN = '(?=\'napari.manifest\')(.*?)(?:\.yaml\')'
NPE2_SETUPPY_FILE_PATTERN = '(?:\=\s)(.*?)(?=\"])'
NPE2_PYPROJECT_MANIFEST_PATTERN = '(?=napari.manifest\")(.*?)(?:\.yaml)'
NPE2_PYPROJECT_FILE_PATTERN = '(?:\:)(.*?)(?=\'\])'
NPE2_FOLDER_LOCATION_PATTERN = '(.*?)(?=\/napari\.yaml)'

SETUPPY_DISPLAY_NAME_PATTERN = '(?:\sname\=\")(.*?)(?=\")'
SETUPPY_SUMMARY_SENTENCE_PATTERN = '(?:\sdescription\=\")(.*?)(?=\")'
SETUPPY_LONG_DESCRIPTION_PATTERN = '(?:long_description\s\=\s)(.*?)(?=\s\n)'
SETUPPY_SOURCE_CODE_PATTERN = '(?:\"Source\sCode\"\:)(.*?)(?=\"\,)'
SETUPPY_AUTHOR_PATTERN = '(?:author\=\")(.*?)(?=\")'
SETUPPY_BUG_TRACKER_PATTERN = '(?:\"Bug\sTracker\"\:)(.*?)(?=\"\,)'
SETUPPY_USER_SUPPORT_PATTERN = '(?:\"User\sSupport\"\:)(.*?)(?=\"\,)'

PYCFG_DISPLAY_NAME_PATTERN = '(?:\sname\s\=\s)(.*?)(?=\s\n)'
PYCFG_SUMMARY_SENTENCE_PATTERN = '(?:\sdescription\s\=\s)(.*?)(?=\s\n)'
PYCFG_LONG_DESCRIPTION_PATTERN = '(?:long_description\s\=\s)(.*?)(?=\s\n)'
PYCFG_SOURCE_CODE_PATTERN = '(?:Source\sCode\s\=\s)(.*?)(?=\s)'
PYCFG_AUTHOR_PATTERN = '(?:author\s\=\s)(.*?)(?=\s\n)'
PYCFG_BUG_TRACKER_PATTERN = '(?:Bug\sTracker\s\=\s)(.*?)(?=\s)'
PYCFG_USER_SUPPORT_PATTERN = '(?:User\sSupport\s\=\s)(.*?)(?=\s)'

FILE_IN_LONG_DESCRIPTION_PATTERN = '(?:file\:\s)(.*?)(?=\s)'
IMAGE_STYLE_PATTERN = '(?:max-width\:\s)(.*?)(?=\%)'
IMAGE_WIDTH_PATTERN ='(?:width\=\")(.*?)(?=\")'
SHIELDS_IO_PATTERN = '(?:img.shields.io)'
